
on: 
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: "login to docker hub "
        run: docker login --username ${{secrets.DOCKER_USERNAME}} --password ${{secrets.DOCKER_TOKEN}}


      - name: "building docker image"
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/proiect .

      - name: "pushing image in docker hub for finall project"
        run: docker push ${{ secrets.DOCKER_USERNAME }}/proiect


